name: exchange
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.2
  cloud_firestore:
  google_sign_in: 4.0.1+1
  firebase_core: 0.3.1+1
  rxdart: ^0.20.0
  http: ^0.12.0+2
  google_maps_flutter: ^0.5.19
  geolocator: ^5.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/sin.jpg
    - assets/flutter.jpeg
    - assets/mail.png
    - assets/ltc.png
